### ISSUE TITLE
Error introduced in e6dd667

### ISSUE THREAD

**Issue by tejasvi** [OokTech/TW5-Bob#162]
Since e6dd667 Bob gives
```$:/plugins/OokTech/Bob/ServerSide.js:802
  if(data.decoded) {
          ^

TypeError: Cannot read property 'decoded' of undefined
    at Object.ServerSide.getViewableSettings ($:/plugins/OokTech/Bob/ServerSide.js:802:11)
    at Object.exports.handler ($:/plugins/OokTech/Bob/ServerRoutes/get-status.js:37:30)
    at SimpleServer.requestHandler ($:/plugins/OokTech/Bob/commands/wsserver.js:155:15)
    at Server.emit (events.js:198:13)
    at parserOnIncoming (_http_server.js:691:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:17)
```
and BobEXE gives,
```$:/plugins/OokTech/Bob/FileSystemMonitor.js:24
if($tw.node && $tw.settings.disableFileWatchers !== 'yes') {
                            ^

TypeError: Cannot read property 'disableFileWatchers' of undefined
    at $:/plugins/OokTech/Bob/FileSystemMonitor.js:24:29
    at $:/plugins/OokTech/Bob/FileSystemMonitor.js:229:3
    at Script.runInContext (vm.js:127:20)
    at Script.runInNewContext (vm.js:133:17)
    at Object.runInNewContext (vm.js:299:38)
    at Object.$tw.utils.evalSandboxed (/root/Bob/TiddlyWiki5/boot/boot.js:530:5)
    at Object.$tw.modules.execute (/root/Bob/TiddlyWiki5/boot/boot.js:806:15)
    at /root/Bob/TiddlyWiki5/boot/boot.js:846:30
    at Object.$tw.utils.each (/root/Bob/TiddlyWiki5/boot/boot.js:135:12)
    at Object.$tw.modules.forEachModuleOfType (/root/Bob/TiddlyWiki5/boot/boot.js:845:12)```


---

I am running (check any that apply, put an x inside the [ ] to check a box, like this: [x]):

- [ ] Windows
- [ ] OSX
- [x] Linux
- [ ] Other

and using

- [x] The nodejs version
- [x] The single file executable

Before posting I read [issue guidelines](./IssueGuidelines.md) and:

- [x] I am using the newest version
- [x] The answer to my question isn't listed in the documentation or this isn't
  a question
- [x] This is not a duplicate issue
- [x] I have not done anything that required me to set acceptance to
  `I Will Not Get Tech Support For This`

**Comment by inmysocks** [comment]
I think both of these should be fixed in the next release. I am hoping to put out the beta to test today
