### ISSUE TITLE
Error updating theme list

### ISSUE THREAD

**Issue by mauloop** [OokTech/TW5-Bob#84]
If I click on "Update Theme List" in "ControlPanel/BobSettings/ManageThemes" the following error message is displayed in the console window I used to launch Bob:

Error getting theme info { Error: Directory 'C:\**\BobEXE\themes' was not included into executable at compilation stage. Please recompile adding it as asset or script.
    at error_ENOENT (pkg/prelude/bootstrap.js:422:17)
    at readdirFromSnapshot (pkg/prelude/bootstrap.js:766:29)
    at Object.fs.readdirSync (pkg/prelude/bootstrap.js:786:12)
    at Object.exports.getThemeInfo ($:/plugins/OokTech/Bob/theme-info.js:29:24)
    at Object.$tw.nodeMessageHandlers.getThemeList ($:/plugins/OokTech/Bob/NodeMessageHandlers.js:1381:34)
    at WebSocket.$tw.Bob.handleMessage ($:/plugins/OokTech/Bob/NodeWebSocketsSetup.js:151:52)
    at WebSocket.emit (events.js:182:13)
    at Receiver.receiverOnMessage ($:/plugins/OokTech/Bob/External/WS/lib/websocket.js:720:20)
    at Receiver.emit (events.js:182:13)
    at Receiver.dataMessage ($:/plugins/OokTech/Bob/External/WS/lib/receiver.js:415:14)
  errno: -4058,
  code: 'ENOENT',
  path: 'C:\\snapshot\\BobEXE\\themes',
  pkg: true }

BobExe 1.2.2rc5

---

I am running (check any that apply, put an x inside the [ ] to check a box, like this: [x]):

- [x] Windows
- [ ] OSX
- [ ] Linux
- [ ] Other

and using

- [ ] The nodejs version
- [x] The single file executable

Before posting I read [issue guidelines](./IssueGuidelines.md) and:

- [x] I am using the newest version
- [x] The answer to my question isn't listed in the documentation or this isn't
  a question
- [x] This is not a duplicate issue
- [x] I have not done anything that required me to set acceptance to
  `I Will Not Get Tech Support For This`

**Comment by inmysocks** [comment]
I see where that error is coming from, I will fix it. Did it actually prevent themes from being listed? It shouldn't have broken anything.

**Comment by mauloop** [comment]
Themes that are included in the BobExe binary are correctly listed. I do not have additional themes in my Themes folder, so I cannot tell if it works too for this case.

**Comment by inmysocks** [comment]
I believe that this is fixed, I will re-open the issue if it persists.
