### ISSUE TITLE
Boblinux executable crashes on server with no GUI installed

### ISSUE THREAD

**Issue by lacikawiz** [OokTech/TW5-Bob#99]
I just set up an Ubuntu Server and wanted to run my Wikis from there. It has no GUI and when I tried to startup the BobLinux executable I got the following error message:

```
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn xdg-open ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

After some looking around I figured out that it crashed because it tried to spawn (execute) the `xdg-open` command & because it does not exist on my system & the error handling code is absent for that case it crashed. 

I got around this issue by creating an empty executable file named `xdg-open` and then Boblinux was able to start with no further problems. 

I believe the fix for this is simple: just add a few lines of code to handle the case when `spawn` does not run correctly. Although, I acknowledge that my situation is a rare case but adding the error handling would make the code more sturdy. 

Thank you for creating this program!

---

I am running (check any that apply, put an x inside the [ ] to check a box, like this: [x]):

- [ ] Windows
- [ ] OSX
- [x] Linux
- [ ] Other

and using

- [ ] The nodejs version
- [x] The single file executable

Before posting I read [issue guidelines](./IssueGuidelines.md) and:

- [x] I am using the newest version
- [x] The answer to my question isn't listed in the documentation or this isn't
  a question
- [x] This is not a duplicate issue
- [x] I have not done anything that required me to set acceptance to
  `I Will Not Get Tech Support For This`

**Comment by inmysocks** [comment]
I added a try-catch block around that code for exactly the reason you have run into, either I did something wrong with that or I haven't released the update yet. I am a bit behind on actually releasing the next update.

In the meantime when the executable ran it should have created a folder called IndexWiki, inside that you can go into the settings folder and in settings.json you can set suppressBrowser to true and it won't try to open the browser.

so the settings.json would be something like this:

```
{
  wikis:{
     //listed wikis here//
  },
  suppressBrowser: true,
  //whatever other settings are here//
}
```

the next version should be out in the next few days with this problem fixed.

**Comment by lacikawiz** [comment]
Awesome! Thank you for the quick response and workaround!

**Comment by inmysocks** [comment]
I do not have a convenient way to test if the update fixed this problem or not, if you have a way to test the new version on a headless setup I would appreciate it if you could let me know if the simple try-catch block was enough to fix the problem.

**Comment by lacikawiz** [comment]
Okay. Thank you! I downloaded the latest executable for Linux and undid the workaround. Unfortunately, the error still seems to be present:

Here's the output:
```
TiddlyWiki version 5.1.21 with Bob version 1.2.4
Serving on 0.0.0.0:8111
(press ctrl-C to exit)
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn xdg-open ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by inmysocks** [comment]
OK, I will set up a headless raspberry pi so I can do real testing. I am not certain why the try catch block didn't work and will need to poke it a bit.

**Comment by inmysocks** [comment]
I once again updated how this is supposed to handle errors, it once again shouldn't crash, but like before I haven't been able to test it.

**Comment by lacikawiz** [comment]
Ok. To test this, should I compile the executable from this repository, or can I use the latest release here: https://github.com/OokTech/TW5-BobEXE/releases ?

**Comment by inmysocks** [comment]
It should be in the newest release.

**Comment by lacikawiz** [comment]
Sorry to report that I still got the following when I had the `suppressBrowser` option turned off: 

```
TiddlyWiki version 5.1.21 with Bob version 1.3.3b
Bob saver server running on 127.0.0.1:61192
Serving on 0.0.0.0:8111
(press ctrl-C to exit)
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn xdg-open ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
